# This file is generated by gyp; do not edit.


LOCAL_PATH := $(call my-dir)
GYP_ABS_ANDROID_TOP_DIR := $(shell pwd)

include $(LOCAL_PATH)/pitchandroid/soundtouch-jni.target.mk
include $(LOCAL_PATH)/soundtouch/soundtouch.target.mk

GYP_FILES := \
  $(LOCAL_PATH)/build/common.gypi\
  $(LOCAL_PATH)/pitchandroid/soundtouch-jni.gyp\
  $(LOCAL_PATH)/soundtouch/soundtouch.gyp

$(LOCAL_PATH)/GypAndroid.mk: PRIVATE_LOCAL_PATH := $(LOCAL_PATH)
$(LOCAL_PATH)/GypAndroid.mk: $(GYP_FILES)
	echo ACTION Regenerating $@
	./build/gyp_build -fandroid --ignore-environment "--toplevel-dir=." -I/Users/harriscao/Documents/workspace_thirdparty/pitchshift/build/common.gypi "--depth=." "-Dlibrary=static_library" "-Dos_posix=1" "-DOS=android" "-Dtarget_arch=arm" "-Dclang=0" "-Dcomponent=static_library" "-Duse_system_stlport=0" "$(PRIVATE_LOCAL_PATH)/pitchandroid/soundtouch-jni.gyp"

# "gyp_all_modules" is a concatenation of the "gyp_all_modules" targets from
# all the included sub-makefiles. This is just here to clarify.
gyp_all_modules:
