/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.soundtouchandroid.core;

public class FrameProcessor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FrameProcessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FrameProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SoundtouchNativeJNI.delete_FrameProcessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FrameProcessor() {
    this(SoundtouchNativeJNI.new_FrameProcessor(), true);
  }

  public void setTempoChange(float temp) {
    SoundtouchNativeJNI.FrameProcessor_setTempoChange(swigCPtr, this, temp);
  }

  public void shiftingPitch(byte[] buffer, int offset, int length) {
    SoundtouchNativeJNI.FrameProcessor_shiftingPitch(swigCPtr, this, buffer, offset, length);
  }

  public void receiveSamples(byte[] buffer, int length) {
    SoundtouchNativeJNI.FrameProcessor_receiveSamples(swigCPtr, this, buffer, length);
  }

  public void flush() {
    SoundtouchNativeJNI.FrameProcessor_flush(swigCPtr, this);
  }

}
