/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.soundtouchandroid.core;

public class SoundtouchNativeJNI {
  public final static native long new_FrameProcessor();
  public final static native void delete_FrameProcessor(long jarg1);
  public final static native void FrameProcessor_setTempoChange(long jarg1, FrameProcessor jarg1_, float jarg2);
  public final static native void FrameProcessor_shiftingPitch(long jarg1, FrameProcessor jarg1_, byte[] jarg2, int jarg3, int jarg4);
  public final static native void FrameProcessor_receiveSamples(long jarg1, FrameProcessor jarg1_, byte[] jarg2, int jarg3);
  public final static native void FrameProcessor_flush(long jarg1, FrameProcessor jarg1_);
  public final static native void WavProcessor_processWav(long jarg1, WavProcessor jarg1_, String jarg2, float jarg3, float jarg4, float jarg5, String jarg6);
  public final static native long new_WavProcessor();
  public final static native void delete_WavProcessor(long jarg1);

  static {
    try {
        System.loadLibrary("soundtouchnative");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

}
