/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.soundtouchandroid.core;

public class WavProcessor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected WavProcessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(WavProcessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SoundtouchNativeJNI.delete_WavProcessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public WavProcessor() {
    this(SoundtouchNativeJNI.new_WavProcessor(), true);
  }

}
