# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := soundtouch_soundtouch_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES :=

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	soundtouch/source/SoundTouch/AAFilter.cpp \
	soundtouch/source/SoundTouch/FIFOSampleBuffer.cpp \
	soundtouch/source/SoundTouch/FIRFilter.cpp \
	soundtouch/source/SoundTouch/cpu_detect_x86.cpp \
	soundtouch/source/SoundTouch/RateTransposer.cpp \
	soundtouch/source/SoundTouch/SoundTouch.cpp \
	soundtouch/source/SoundTouch/TDStretch.cpp \
	soundtouch/source/SoundTouch/BPMDetect.cpp \
	soundtouch/source/SoundTouch/PeakFinder.cpp


# Flags passed to both C and C++ files.
MY_CFLAGS :=

MY_CFLAGS_C :=

MY_DEFS := \
	'-DANDROID' \
	'-DST_NO_EXCEPTION_HANDLING'

LOCAL_CFLAGS := $(MY_CFLAGS_C) $(MY_CFLAGS) $(MY_DEFS)

# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/soundtouch/include \
	$(LOCAL_PATH)/soundtouch/source/SoundTouch

LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES)

# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS :=

### Rules for final target.

LOCAL_LDFLAGS :=


LOCAL_STATIC_LIBRARIES :=

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES :=

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: soundtouch_soundtouch_gyp

# Alias gyp target name.
.PHONY: soundtouch
soundtouch: soundtouch_soundtouch_gyp

include $(BUILD_STATIC_LIBRARY)
